// ============================================================
// KIMBIZ - TOP SELLING PRODUCTS
// ============================================================
// Displays the products that are currently generating the most
// sales for the business.
//
// For now, the component uses sample data.
// Later, this information will come from our database.
// ============================================================


// ============================================================
// PRODUCT DATA
// ============================================================
// Each object represents one product.
//
// name    → product name
// sold    → number of units sold
// revenue → revenue generated by the product
// ============================================================

const products = [
  {
    name: "Nike Air Max",
    sold: 42,
    revenue: 84000,
  },
  {
    name: "Adidas Superstar",
    sold: 35,
    revenue: 70000,
  },
  {
    name: "Puma Runner",
    sold: 28,
    revenue: 56000,
  },
  {
    name: "New Balance 574",
    sold: 24,
    revenue: 48000,
  },
];


// ============================================================
// TOP SELLING PRODUCTS COMPONENT
// ============================================================

export default function TopSellingProducts() {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">

      {/* ======================================================
          SECTION HEADER
          ====================================================== */}

      <div className="mb-6">

        <h2 className="text-lg font-semibold text-slate-900">
          Top Selling Products
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Your best-performing products.
        </p>

      </div>


      {/* ======================================================
          TABLE HEADER
          ------------------------------------------------------
          We use a grid instead of a traditional HTML table
          because this gives us more control over the layout.
          ====================================================== */}

      <div className="grid grid-cols-3 border-b border-slate-200 pb-3 text-xs font-medium uppercase tracking-wide text-slate-400">

        <span>Product</span>

        <span className="text-center">
          Sold
        </span>

        <span className="text-right">
          Revenue
        </span>

      </div>


      {/* ======================================================
          PRODUCT LIST
          ------------------------------------------------------
          .map() creates one row for every product in our
          products array.
          ====================================================== */}

      <div>

        {products.map((product, index) => (

          <div
            key={index}
            className="grid grid-cols-3 items-center border-b border-slate-100 py-4 last:border-b-0"
          >

            {/* Product name */}

            <span className="text-sm font-medium text-slate-900">
              {product.name}
            </span>


            {/* Number of units sold */}

            <span className="text-center text-sm text-slate-600">
              {product.sold}
            </span>


            {/* Revenue generated */}

            <span className="text-right text-sm font-medium text-slate-900">
              KSh {product.revenue.toLocaleString()}
            </span>

          </div>

        ))}

      </div>

    </div>
  );
}